[package]
name = "tankrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "game_lib"
path = "src/lib.rs"
required-features = ["bevy_xpbd_3d"]

[dependencies]
bevy = { version = "0.14.2", features = ["wayland"] }
rand = "0.8.5"
