# inspired by https://github.com/danth/stylix/blob/master/.github/workflows/docs.yml
name: Rust-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: |
            extra-experimental-features = nix-command flakes

      - name: Set up cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build docs
        run: nix -L build github:${{ github.repository }}/${{ github.sha }} --no-write-lock-file

      - name: Prepare docs for upload
        run: cp -r --dereference --no-preserve=mode,ownership result/ public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
